### ISSUE TITLE
Two types of background color

### ISSUE THREAD

**Issue by j0hannes** [NLKNguyen/papercolor-theme#83] opened 2017-02-10 15:55 UTC
I've only seen this using the papercolor scheme:

![screenshot_20170210_165236](https://cloud.githubusercontent.com/assets/3944397/22833299/a63c9076-efb1-11e6-9d05-155501baf429.png)

**Comment by NLKNguyen** [comment] 2017-02-11 03:16
What is your environment (OS, terminal emulator, tmux or not, etc.)?
Does it go away if you change background back & forth (:set background=light/dark)?

**Comment by j0hannes** [comment] 2017-02-11 20:43
I see the same behaviour on two configurations:

1) yakuake on Arch, using tmux and screen inside
2) iTerm2 on OSX, using only screen

Interestingly, everything seems to be OK if I skip tmux under linux. On OSX, I usually don't use tmux and still see the same pattern.

Changing the background option doesn't help.

**Comment by pickfire** [comment] 2017-02-12 15:25
@j0hannes Can you try not to use screen screen? What's your `$TERM` in screen and tmux? Can you try `set t_Co=256` or `set termguicolor` (if you use a true color terminal)? What's your vim or neovim version?

**Comment by j0hannes** [comment] 2017-02-12 16:57
* vim version is 7.4.576
  * `set t_Co=256` has no effect
  * `set termguicolor` isn't recognized by vim
  * `$TERM` is `screen-256color-bce` inside screen and `xterm-256color` outside
    *  overwriting `$TERM` aka `TERM=xterm-256color vi ...` has no effect
  * not using screen also has no effect
    * those fragments only disappear if I don't use tmux, but only on Arch (doesn't help for OSX)

**Comment by pickfire** [comment] 2017-02-14 04:06
@j0hannes What terminal are you using? When it is working, what type of environment (os, term, `$TERM`, multiplexer) is it on? And on what type of environment does it break? I am a bit confuse now.

And if you are on tmux in Arch, try setting the `$TERM` to `screen-256color` because IIRC there some some problems with tmux terminfo being too new.

**Comment by NLKNguyen** [comment] 2017-02-14 20:32
@j0hannes try running this command and please post your screenshot. It will not be nice, but I only want to know if it helps unify the background colors.
```
:hi Normal ctermbg=none
```

**Comment by j0hannes** [comment] 2017-02-16 19:30
Yes, that helps:

![screenshot_20170216_202941](https://cloud.githubusercontent.com/assets/3944397/23037465/bb6e1b34-f486-11e6-9c2f-b805180a02c8.png)

**Comment by j0hannes** [comment] 2017-02-16 19:35
@pickfire It breaks in both configurations that I describe in my second post. One is with the other without tmux.

I already let tmux pretend to be screen:
`set -g default-terminal "screen-256color"`

Inside screen, it's set to `screen-256color-bce`.

**Comment by pickfire** [comment] 2017-02-18 04:20
@j0hannes Looks like @NLKNguyen answer helps. Maybe you can also look at http://stackoverflow.com/questions/4325682/vim-colorschemes-not-changing-background-color/23982923

**Comment by NLKNguyen** [comment] 2017-02-21 06:33
I will try to fix this. I use iTerm2. Could you list the minimal steps to reproduce this issue? I haven't used screen. So if it's can be replicated with tmux, it's better.

**Comment by j0hannes** [comment] 2017-02-21 18:08
On Arch, I get the faulty background when performing the following steps:

1. Open tmux (`$TERM` is `xterm-256color`)
2. Open vim (minimal vimrc to reproduce the error below)

This is how the result looks like:
![screenshot_20170221_190331](https://cloud.githubusercontent.com/assets/3944397/23177808/7dceb0a0-f868-11e6-87a3-03287bf4fd67.png)

```vim
syn on
set number
set background=dark
colorscheme PaperColor
```

**Comment by NLKNguyen** [comment] 2017-02-21 19:17
I couldn't reproduce that in either iTerm2 or default Terminal app on Mac. I tried reducing colors and stuff but couldn't get the behavior. I remember I got into similar backgrounds issue when I use Windows Putty to SSH to a Linux box. I believe it's because of the deficiency of terminal emulator. Quick solution is to use a better emulator. 

Since I can't replicate the issue, right now I can only make a guess of how it might be fixed with the latest commit https://github.com/NLKNguyen/papercolor-theme/commit/cfbda6dab4c2db8b7b85d9050a8e99e36c1e3626 . Please try it and let me know if it effects anything.

**Comment by j0hannes** [comment] 2017-02-21 19:25
I see the same behaviour using iTerm2, so which better terminal emulator could I switch to?

I tried the latest commit but it didn't affect the background colours.

**Comment by NLKNguyen** [comment] 2017-02-21 19:51
I think I've just been able to replicate the issue in iTerm2. Might be applicable to other emulators.

Install & start up
```
$ brew install tmux
$ tmux
```

In tmux session:

Here is how I couldn't see the issue

```
$ echo $TERM
screen

$ vim
```

but if I set the TERM to xterm-256color
```
$ export TERM="xterm-256color"
$ vim
```

I get the problem
<img width="1022" alt="screen shot 2017-02-21 at 11 41 10 am" src="https://cloud.githubusercontent.com/assets/4667129/23181707/d1707754-f82a-11e6-9063-a9a65ac686f1.png">

So I think if you set TERM to "screen" in tmux, it would be fine. Also, maybe an option to set the background to transparent in order to use the terminal background would be the last resort.

**Comment by NLKNguyen** [comment] 2017-02-21 19:58
Another reference: http://superuser.com/questions/399296/256-color-support-for-vim-background-in-tmux
Seems like it's tmux environment setting issue. Strangely enough, I don't have any tmux custom settings, and I don't even use "tmux -2", but I didn't see the problem. It could be that new tmux updates already handle things better by default.

**Comment by j0hannes** [comment] 2017-02-21 20:21
Regarding the TERM setting, I remember that I had to set it to a 256 color profile in order to allow for full colour support in some applications. But that was a long time ago; maybe it's not necessary anymore.

In addition, I see the same behaviour using iTerm2 and screen.

What does `hi Normal ctermbg=none` do? When I put it to my vimrc everything looks fine.

**Comment by NLKNguyen** [comment] 2017-02-21 23:31
That command sets the normal text background to nothing, i.e. transparent, so the terminal background will be used and not the theme background color.

I added an option to use terminal background. Put this in your `.vimrc`
```VimL
let g:PaperColor_Theme_Options = {
  \   'transparent_background': 1
  \ }
```
If you want the exact background color like the dark theme, then set your terminal background to this `#1c1c1c`

**Comment by j0hannes** [comment] 2017-02-22 17:42
That looks good now 👍 

I still wonder why some whitespaces are printed with a different background colour (or without).

**Comment by NLKNguyen** [comment] 2017-02-22 19:46
I don't really know. Probably just old code. Hope it will become less of a problem in future software updates.

Glad it works now 😄

**Closed by NLKNguyen** 2017-02-22 19:46 UTC
